CREATE DATABASE Usersdb;
USE Usersdb;
CREATE TABLE Users ( 
id INT NOT NULL AUTO_INCREMENT, 
Name VARCHAR(255) NOT NULL,
Nickname VARCHAR(255),
Age int NOT NULL,
Bio VARCHAR(255),
PRIMARY KEY (id)
);



